version: "3.9"
services:
  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

  vpn:
    image: "dperson/openvpn-client"
    dns: 8.8.4.4
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1080:1080" # socks-proxy
      - "3128:3128" # http-proxy
    volumes:
      - ./vpn/config:/vpn
    healthcheck:
      test: "[[ ${EXTERNAL_IP} != $$(curl -LSs 'https://api.ipify.org') ]]"
      interval: 30s
      timeout: 5s
      retries: 5
    restart: on-failure
    command: -f "" -a "${USERNAME};${PW}"
      
  http-proxy:
    build:  ./http-proxy
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    volumes:
      - ./http-proxy/squid.conf:/etc/squid/squid.conf
    healthcheck:
      test: "[ ${EXTERNAL_IP} != $$(curl -x http://localhost:3128 -LSs 'https://api.ipify.org') ]"
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  socks-proxy:
    build:  ./socks-proxy
    depends_on:
      vpn:
        condition: service_healthy
    user:
      root
    network_mode: "service:vpn"
    volumes:
      - ./socks-proxy/sockd.conf:/etc/dante/sockd.conf
    healthcheck:
      test: "[ ${EXTERNAL_IP} != $$(curl -x socks5h://vpn:1080 -LSs 'https://api.ipify.org') ]"
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

